import React from 'react';

export default function Page() {
  return (
    <main className="min-h-screen p-8 max-w-4xl mx-auto">
      <h1 className="text-3xl font-bold mb-4">Study Abroad</h1>
      <p className="text-gray-600">This page was auto-generated by the admin dashboard system.</p>
    </main>
  );
}
